theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "music"
marquee = false
max_width = 21
format = "{combo}"
player = "spotify"
hide_when_empty = true
buttons = ["play", "next"]

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "temperature"
collapsed = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"

[[block]]
block = "load"
interval = 5

[[block]]
block = "battery"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

