-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--
-- fold_init = vim.api.nvim_create_augroup("treesitter_fold_init", { clear = true })
-- vim.api.nvim_create_autocmd({ "BufReadPost", "FileReadPost" }, {
--   group = fold_init,
--   command = "normal zR",
-- })
